# FL DATA
DATASET: "mnist"
TOTAL_CLIENTS: 100 # total clients 10|100
CLIENT_FRAC: 0.2 # client fraction to select in each round 0.1|0.2|0.4
POISON_FRAC: 0.2 # poisoned fraction for environment 0.0|0.1|0.2|0.3|0.4|0.5|0.6
CLASS_RATIO: 10 # class ratio in client data distribution, choose 1|4|10

# FL SETTINGS
MODEL: "nnet" # model to be used
LEARNING_RATE: 0.001 # client's model learning rate
LOCAL_EPOCHS: 10 # epochs to run before clients send back the model update
FED_ROUNDS: 30 # federated rounds to run

# COS_DEFENCE SETTINGS
COS_DEFENCE: True # to turn on cos_defence
CONSIDER_LAYERS: "l1"  # choose layers for grad collection f2|f1|f1l1|l1|l2|all
GRAD_COLLECTION_START: 0   # when to start collecting grads 
GRAD_COLLECT_FOR: -1   #for how many FL rounds grads are collected, -1 decides on dataset
CLUSTER_SEP: 0.01   # seperation between clusters to consider them important
ALPHA: 0.8   # parameter for updating system trust vector
BETA: 0.8    # parameter for updating system trust matrix
GAMMA: 0.1   # decides how much initial trust worthy clients in the environment
TRUST_INC: 2
TRUST_MODIFY_STRATEGY: 1  # 0 for using clustering method to segregate, 1 for AFA, 2 for none
HONEST_PARDON_FACTOR: 1.0 # pardoning factor for good clients getting bad trust values
TRUST_SAMPLING: True # to fill matix by sampling during phase transitions
TRUST_NORMALIZATION: False # to normalize trust values before filling in the matrix